BBCompSep:
    sampler: 'emcee'
    nwalkers: 256
    n_iters: 40000
    likelihood_type: 'h&l'
    pol_channels: ['B']
    l_min: 30
    l_max: 300

    cmb_model:
        cmb_templates: ["./examples/data/camb_lens_nobb.dat", 
                        "./examples/data/camb_lens_r1.dat"]
        params:
            r_tensor: ['r_tensor', 'tophat', [-1., 0., 1.]]
            A_lens: ['A_lens', 'tophat', [0., 1., 10.]]

    fg_model:
        component_1:
            name: Dust
            sed: Dust
            cl:
                BB: ClPowerLaw
            sed_parameters:
                beta_d: ['beta_d', 'tophat', [0.1, 1.53, 10.]]
                temp_d: ['temp', 'fixed', [19.6]]
                nu0_d: ['nu0', 'fixed', [353.]]
            cl_parameters:
                BB:
                   amp_d_bb: ['amp', 'tophat', [0., 20., "inf"]]
                   alpha_d_bb: ['alpha', 'tophat', [-4., -0.2, 1.]]
                   l0_d_bb: ['ell0', 'fixed', [80.]]
            cross:
                epsilon_ds: ['component_2', 'tophat', [-1., 0.2, 1.]]

        component_2:
            name: Synchrotron
            sed: Synchrotron
            cl:
                BB: ClPowerLaw
            sed_parameters:
                beta_s: ['beta_pl', 'tophat', [-10., -3.1, 0.]]
                nu0_s: ['nu0', 'fixed', [23.]]
            cl_parameters:
                BB:
                    amp_s_bb: ['amp', 'tophat', [0., 5., "inf"]]
                    alpha_s_bb: ['alpha', 'tophat', [-4., -0.6, 1.]]
                    l0_s_bb: ['ell0', 'fixed', [80.]]

    systematics:
        bandpasses:
            bandpass_1:
                parameters:
                    #shift_1: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_1: ['gain', 'tophat', [0.95, 1., 1.03]]
            bandpass_2:
                parameters:
                    #shift_2: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_2: ['gain', 'tophat', [0.95, 1., 1.03]]
            bandpass_3:
                parameters:
                    #shift_3: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_3: ['gain', 'tophat', [0.95, 1., 1.03]]
            bandpass_4:
                parameters:
                    #shift_4: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_4: ['gain', 'tophat', [0.95, 1., 1.03]]
            bandpass_5:
                parameters:
                    #shift_5: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_5: ['gain', 'tophat', [0.95, 1., 1.03]]
            bandpass_6:
                parameters:
                    #shift_6: ['shift', 'tophat', [-0.1, 0., 0.1]]
                    gain_6: ['gain', 'tophat', [0.95, 1., 1.03]]
